version: '3'
services:
# 先启动3个zookeeper
    zoo1:
        image: zookeeper
        restart: always
        container_name: zk01
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        container_name: zk02
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        container_name: zk03
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888
# 接着启动3个 journal node
    jnnode01:
        container_name: jn01
        build:
            context: ./journal-node
    jnnode02:
        container_name: jn02
        build:
            context: ./journal-node
    jnnode03:
        container_name: jn03
        build:
            context: ./journal-node        
# 启动一个namenode
    namenode01:
        container_name: node01
        image: zhuanxuhit/hadoop
        restart: always    
        ports:
            - "50070:50070"
            - "8080:8088"
            - "19888:19888"
    namenode02:
        container_name: node02  
        image: zhuanxuhit/hadoop
        restart: always 
        ports:
            - "50071:50070"
            - "8081:8088"
            - "19889:19888"
    datanode01:
        container_name: slave01  
        image: zhuanxuhit/hadoop
        restart: always     
        # deploy:
        #     mode: replicated
        #     replicas: 3
            
    # jn02:
    #     build:
    #         context: ./journal-node
    # jn03:
    #     build:
    #         context: ./journal-node                
# networks:
#   default:
#     external:
#       name: hadoop-network
